### PR TITLE
Adds discord and forum links to the RoboCup resources page

### PR DESCRIPTION
**Pull request by ysims**
Addresses #160.

### CODE REVIEW

**Review by LachlanCourt — COMMENTED** [review]
Is the discord link definitely set to not expire? They usually expire within 7 days by default

**Comment by LachlanCourt** [comment]
This link goes to the off topic channel - I don't know if that's a major drama, it depends on what channel you have focussed when you create the invite

**Comment by ysims** [comment]
> This link goes to the off topic channel - I don't know if that's a major drama, it depends on what channel you have focussed when you create the invite

Ohh I didn't realise it'd do that. I did make it not expire though. I'll update it.

**Review by LachlanCourt — APPROVED** [review]
Iconic

**Review by KipHamiltons — APPROVED** [review]
Let's get this merged

**Pull request merged**
