### PR TITLE
Add a Code of Conduct

### PR DESCRIPTION
**Pull request by ysims**
The code of conduct is the University of Newcastle's code of conduct. 
Added to readme and footer.
Added Netlify badge to footer
[Preview.](https://deploy-preview-59--nubook.netlify.app/)

### CODE REVIEW

**Comment by Bidski** [comment]
Not sure I agree on the positioning of the netlify logo and code of conduct positioning in the footer, makes the left side look unblanaced

**Comment by JosephusPaye** [comment]
I can have a look at this later. Will also need to position the badge correctly on mobile.

**Comment by Bidski** [comment]
Looks ok on mobile. Havent checked desktop yet

**Comment by Bidski** [comment]
Cheater!

**Pull request merged**
