### PR TITLE
Add instructions for NUpbr

### PR DESCRIPTION
**Pull request by ysims**
Up to date instructions. The readme instructions don't seem to work, but this seems to consistently work.

### CODE REVIEW

**Review by Crafty15 — APPROVED** [review]
Tested this personally. LGTM

**Review by BaileyJoe — APPROVED** [review]
Looks consistent with my process the last time I installed NUpbr. LGTM.

**Comment by jpptm** [comment]
Do we want to account for non-members asking for the resources folder now? How do we want to possible deal with that in the future?

**Comment by ysims** [comment]
> Do we want to account for non-members asking for the resources folder now? How do we want to possible deal with that in the future?

Not really, I think there would be copywrite issues with distributing the resources folder publicly. We could consider designing a new folder without these issues.

**Pull request merged**
