### PR TITLE
Auto scroll sidebar to active link on load

### PR DESCRIPTION
**Pull request by JosephusPaye**
This PR ensures that the active link in the sidebar is visible by scrolling to it on page load.

### CODE REVIEW

**Comment by JosephusPaye** [comment]
@ysims I'm tempted to abandon this - most solutions I can think of have caveats that make them not always work. May not be worth the effort and additional code.

**Comment by BrendanAnnable** [comment]
Could you use [Element#ScrollIntoView](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView)?

**Comment by JosephusPaye** [comment]
Was just about to reach out, Brendan.

I think I tried `Element#ScrollIntoView` and got mixed results but don't recall what the problem was exactly.

I'll give it another go.

**Comment by JosephusPaye** [comment]
I think the issue I was concerned about was the scrollbar visibly jumping from the top when navigating pages:

nubook-sidebar-scroll

Seems like something we could live with though.

**Comment by JosephusPaye** [comment]
@ysims Could you try to see if it has the same problem you saw before?

**Comment by ysims** [comment]
The problem has gone now :)

**Pull request merged**
