### PR TITLE
Adds important supplement to Page Not Found page

### PR DESCRIPTION
**Pull request by LachlanCourt**
[Preview](https://deploy-preview-144--nubook.netlify.app/a)
error404

### CODE REVIEW

**Review by TrentHouliston — COMMENTED** [review]
That gif might be a bit big for a 404 1MB isn't so small... maybe cut off the end after the ball stops moving?
Also can the GIF be optimised at all?

**Comment by LachlanCourt** [comment]
It's already pretty shocking quality 😅 I'll run it through an optimiser
I thought the bit where it rolls onto it's back was funny!

**Comment by BrendanAnnable** [comment]
giphy.com uses webp, can we do that? :D

**Comment by LachlanCourt** [comment]
I'll look into it

**Comment by BrendanAnnable** [comment]
For the record, I just meant giphy (a large GIF provider service), actually uses the animated WebP file format instead of GIF. This is because GIF is a terrible file format.

We can still host the file locally in the repo without using giphy as an embed, but just saving it as a `.webp` file, which should be much much much smaller (and higher quality).

**Comment by LachlanCourt** [comment]
It ends up being about the same file size :(

**Comment by KipHamiltons** [comment]
This is brilliant :joy:

**Review by ysims — APPROVED** [review]
LGTM 😄

**Pull request merged**
