### PR TITLE
Improve Markdown content styles

### PR DESCRIPTION
**Pull request by JosephusPaye**
This refactors the CSS applied to markdown content and fixes a number of issues with things like:

- [Code](https://deploy-preview-26--nubook.netlify.com/kitchen-sink#headers-with-code) and [links](https://deploy-preview-26--nubook.netlify.com/kitchen-sink#headers-with-links) nested in headings
- Paragraphs, links, code, math, etc nested in [alerts](https://deploy-preview-26--nubook.netlify.com/kitchen-sink#alerts)
- Paragraphs, links, code, math, etc nested in [blockquotes](https://deploy-preview-26--nubook.netlify.com/kitchen-sink#blockquotes)
- Paragraphs, links, code, math, etc nested in [`<details>`](https://deploy-preview-26--nubook.netlify.com/kitchen-sink#collapsible-content)
- Arbitrarily nested [ordered and unordered lists](https://deploy-preview-26--nubook.netlify.com/kitchen-sink#lists)

[Preview updated kitchen sink](https://deploy-preview-26--nubook.netlify.com/kitchen-sink)

### CODE REVIEW

**Comment by ysims** [comment]
Does KaTeX work inside these too?

**Comment by Bidski** [comment]
Are the lists meant to be coloured? Because I see no colours in the kitchen sink link

**Comment by JosephusPaye** [comment]
> Does KaTeX work inside these too?

Yep, just added a test for those in the kitchen sink.

**Comment by JosephusPaye** [comment]
> Are the lists meant to be coloured? Because I see no colours in the kitchen sink link

You mean the background color behind numbers?

image

I just made it lighter so it's not visually overloading for cases where there're many nested numbers next to each other.

**Comment by Bidski** [comment]
image

**Comment by JosephusPaye** [comment]
Yeah those ones are just gray. Unfortunate choice of item label.

**Comment by Bidski** [comment]
Have we considered alerts in lists, blockquotes, and collapsible content?

**Comment by Bidski** [comment]
If they are fine then this all looks good to me

**Comment by JosephusPaye** [comment]
> Have we considered alerts in lists, blockquotes, and collapsible content?

Just added a test for that and made a few tweaks.

**Comment by JosephusPaye** [comment]
Merging now, any further changes can come later.

**Pull request merged**
